### ISSUE TITLE
demo启动直接报错，Uncaught DOMException: Failed to construct 'Worker'

### ISSUE THREAD

**Issue by Rebellioncry** [langhuihui/H5RtmpClient#203]
完整报错：
Uncaught DOMException: Failed to construct 'Worker': Script at 'file:///C:/Users/admin/Downloads/demo/public/decoder.js' cannot be accessed from origin 'null'.
    at new DecoderWorker (file:///C:/Users/admin/Downloads/demo/public/jessibuca.js:8315:27)
    at new Player (file:///C:/Users/admin/Downloads/demo/public/jessibuca.js:11245:29)
    at Jessibuca._initPlayer (file:///C:/Users/admin/Downloads/demo/public/jessibuca.js:11945:20)
    at new Jessibuca (file:///C:/Users/admin/Downloads/demo/public/jessibuca.js:11919:11)
    at create (file:///C:/Users/admin/Downloads/demo/public/3x3-demo.html:220:25)
    at file:///C:/Users/admin/Downloads/demo/public/3x3-demo.html:249:9
最新版里的demo，打开压缩包里的任意一个html都报这个错

**Comment by bosscheng** [comment]
别用file 协议 用http 协议
