### ISSUE TITLE
useWCS: true； 控制台报错 Uncaught DOMException: Failed to execute 'decode' on 'VideoDecoder': Cannot call 'decode' on a closed codec.     at Pe.decodeVideo (http://localhost:8100/jessibuca.js:1:87224)

### ISSUE THREAD

**Issue by nieliSunboy** [langhuihui/H5RtmpClient#204]
Uncaught DOMException: Failed to execute 'decode' on 'VideoDecoder': Cannot call 'decode' on a closed codec.
    at Pe.decodeVideo (http://localhost:8100/jessibuca.js:1:87224)
    at We._doDecoderDecode (http://localhost:8100/jessibuca.js:1:83822)
    at e (http://localhost:8100/jessibuca.js:1:83065)

**Comment by nieliSunboy** [comment]
用的是 vue 的那个例子

**Comment by bosscheng** [comment]
@nieliSunboy 试下最新版本看看呢。
