### ISSUE TITLE
PC端 谷歌浏览器缩小再放大、或者切换到其他应用再到浏览器会报这个上下文丢失的错误

### ISSUE THREAD

**Issue by fanxiongbin** [langhuihui/H5RtmpClient#214]
这是什么问题呢

WebGL: CONTEXT_LOST_WEBGL: loseContext: context lost

Uncaught DOMException: Failed to execute 'transferToImageBitmap' on 'OffscreenCanvas': ImageBitmap construction failed
    at Object.draw (http://127.0.0.1:10081/ajax/libs/box/jessibuca/decoder.js:7775:52)
    at methodCaller_void_$unsigned$int_unsigned$int_unsigned$int_unsigned$int$ (eval at new_ (http://127.0.0.1:10081/ajax/libs/box/jessibuca/decoder.js:4985:26), <anonymous>:8:26)
    at __emval_call_void_method (http://127.0.0.1:10081/ajax/libs/box/jessibuca/decoder.js:5676:6)
    at wasm://wasm/00401b2a:wasm-function[77]:0x62a7
    at wasm://wasm/00401b2a:wasm-function[61]:0x3382
    at wasm://wasm/00401b2a:wasm-function[76]:0x600f
    at wasm://wasm/00401b2a:wasm-function[73]:0x5e83
    at VideoDecoder.VideoDecoder$decode [as decode] (eval at new_ (http://127.0.0.1:10081/ajax/libs/box/jessibuca/decoder.js:4985:26), <anonymous>:10:10)
    at _doDecode (http://127.0.0.1:10081/ajax/libs/box/jessibuca/decoder.js:7834:25)
    at loop (http://127.0.0.1:10081/ajax/libs/box/jessibuca/decoder.js:7860:16)

**Comment by fanxiongbin** [comment]
页面一共显示8个视频画面，http-flv流，只要一直显示浏览器页面就不会报错

**Comment by fanxiongbin** [comment]
![image](https://user-images.githubusercontent.com/21343025/176990600-cd2731a8-07ce-4212-a196-2ace098fbd88.png)

**Comment by bosscheng** [comment]
看着像离屏渲染的问题。先禁用试试看呢。离屏渲染的坑太多了[哭]。
