### ISSUE TITLE
播放wss视频流报错，视频流有二进制消息，播放不了

### ISSUE THREAD

**Issue by WEB-M-M-T** [langhuihui/H5RtmpClient#274]
decoder.js:1 Uncaught TypeError: Failed to execute 'configure' on 'VideoDecoder': Failed to parse codec string.
    at Object.decode (decoder.js:1:75833)
    at r (decoder.js:1:81034)
    at decoder.js:1:81436

**Comment by WEB-M-M-T** [comment]
开启 了硬解码的原因
