### ISSUE TITLE
memory access out of bounds

### ISSUE THREAD

**Issue by yyhLogin** [langhuihui/H5RtmpClient#304]
播放国标实时视频控制台出现错误:memory access out of bounds
decoder.wasm:1 Uncaught RuntimeError: memory access out of bounds
    at decoder.wasm
    at decoder.js:1:12912
    at Object.toWireType (decoder.js:1:80978)
    at VideoDecoder.VideoDecoder$decode [as decode] (eval at Br (decoder.js:1:62101), <anonymous>:8:26)
    at r (decoder.js:1:108726)
    at decoder.js:1:109199
用的最新版2.19的版本

**Comment by bosscheng** [comment]
@yyhLogin 播放的视频格式是啥？H264？ H265？  还有分辨率是多少？

**Comment by yyhLogin** [comment]
@bosscheng 视频格式是H264，音频格式是PCMA， 分辨率640-480和1280-720都试过，均会出现这个问题，上面的信息是视频报错，音频报错的也有
decoder.wasm:1 Uncaught RuntimeError: memory access out of bounds
    at decoder.wasm
    at decoder.js:1:12912
    at Object.toWireType (decoder.js:1:80978)
    at AudioDecoder.AudioDecoder$decode [as decode] (eval at Br (decoder.js:1:62101), <anonymous>:8:26)
    at r (decoder.js:1:108726)
    at decoder.js:1:109199

**Comment by bosscheng** [comment]
@bosscheng 方便给个流？复现看下

**Comment by bosscheng** [comment]
@yyhLogin 方便给个流？复现看下

**Comment by yyhLogin** [comment]
> @yyhLogin 方便给个流？复现看下

方便加个q或者V吗

**Comment by bosscheng** [comment]
@yyhLogin  bosswancheng  

备注：github

**Comment by yyhLogin** [comment]
> @yyhLogin bosswancheng
> 
> 备注：github

已经加了，你通过以下
